language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version
  - docker build -t udagram-reverseproxy ./reverseproxy
  - docker tag udagram-reverseproxy yassineghorbal/reverseproxy:v1
  - docker build -t udagram-api-user ./udagram-api-user
  - docker tag udagram-api-user yassineghorbal/udagram-api-user:v1
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker tag udagram-api-feed yassineghorbal/udagram-api-feed:v1
  - docker build -t udagram-frontend ./udagram-frontend
  - docker tag udagram-frontend yassineghorbal/udagram-frontend:v1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push yassineghorbal/reverseproxy:v1
  - docker push yassineghorbal/udagram-api-user:v1
  - docker push yassineghorbal/udagram-api-feed:v1
  - docker push yassineghorbal/udagram-frontend:v1
